// Seed original: 12 eixos + ~50 ramificações + 10 conexões (apresentação 02/07/2026).
// Fonte: app/mapa-rizomatico-cip.html. Usado para semear o banco e para o botão "restaurar".
import { N } from './model.js';

export const SEED = {
  v: 4,
  nodes: [
    N('cip', null, 'centro', 'CIP Olinda', 'Centro de Interpretação do Patrimônio do Centro Histórico de Olinda — Casarão Hermann Lundgren. Pesquisa OCCA, 3 meses.', { status: 'fazendo' }),
    N('e1', 'cip', 'eixo', '1 · Mapa Turístico', 'Mapa de setorização com monitor touch: equipamentos tombados de cultura e turismo do Centro Histórico.'),
    N('e2', 'cip', 'eixo', '2 · Casarão Lundgren', 'A Edificação / Restauro e Retrofit do Casarão Hermann Lundgren (séc. XIX, bairro do Carmo).', { status: 'afazer', notes: 'Prioridade mês 1 — documentação possivelmente privada.' }),
    N('e3', 'cip', 'eixo', '3 · Patrimônio Imaterial', 'Galeria imersiva: Frevo, Bonecos Gigantes, Maracatu, Caboclinhos, Tapioca Olindense.'),
    N('e4', 'cip', 'eixo', '4 · Linha do Tempo', 'Painel com os marcos temporais do Centro Histórico, de 1535 à atualidade.'),
    N('e5', 'cip', 'eixo', '5 · Gênese: Paisagem', 'Paisagem natural na fundação (1535, Duarte Coelho); cenografia e projeções.', { status: 'afazer', notes: 'Prioridade mês 1 — acervos raros e internacionais (Frans Post).' }),
    N('e6', 'cip', 'eixo', '6 · Traçado Urbano', 'Urbanização do Centro Histórico a partir do Alto da Sé: plantas, planos, mapas, imagens aéreas.'),
    N('e7', 'cip', 'eixo', '7 · Bonde: Trilho das Épocas', 'Bonde cenográfico dos Bondes Elétricos de Olinda (1914–1950); arquitetura e paisagem do percurso.', { status: 'afazer', notes: 'Prioridade mês 1 — iconografia dispersa em coleções privadas.' }),
    N('e8', 'cip', 'eixo', '8 · Aloísio Magalhães', 'Painéis táteis com litogravuras; biografia e luta pelo título UNESCO.', { status: 'afazer', notes: 'Prioridade mês 1 — direitos sobre o Álbum Olinda.' }),
    N('e9', 'cip', 'eixo', '9 · Postais e Selos', 'Móbile com monóculos: cartões postais e selos antigos de Olinda + terminal de pesquisa.', { status: 'afazer', notes: 'Risco máximo — colecionadores privados. Primeiro contato do projeto.' }),
    N('e10', 'cip', 'eixo', '10 · Midiateca', 'Terminais de consulta: publicações, teses, artigos e audiovisual sobre o Centro Histórico.'),
    N('e11', 'cip', 'eixo', '11 · Gastronomia & Arte', 'Café bistrô + núcleo de artesanato: gastronomia e artistas olindenses.'),
    N('e12', 'cip', 'eixo', '12 · Maracatu Nação PE', 'Núcleo do Maracatu Nação Pernambuco, residente no local há mais de uma década.'),
    N('e1-inv', 'e1', 'ramo', 'Inventário de equipamentos', 'Principais equipamentos de cultura e turismo tombados que entram no mapa.'),
    N('e1-sin', 'e1', 'ramo', 'Sinopses dos espaços', 'Importância de cada espaço e acervo correspondente, em pílulas.'),
    N('e1-dad', 'e1', 'ramo', 'Dados práticos', 'Localização, distância, como chegar — para o monitor touch.'),
    N('e1-ico', 'e1', 'ramo', 'Iconografia', 'Imagens em alta resolução de cada equipamento.'),
    N('e2-hist', 'e2', 'ramo', 'História e família Lundgren', 'Origem da edificação e trajetória da família Hermann Lundgren.'),
    N('e2-arq', 'e2', 'ramo', 'Características arquitetônicas', 'Tipologia senhorial, fachada simétrica, alvenaria portante, telha cerâmica.'),
    N('e2-usos', 'e2', 'ramo', 'Usos ao longo do tempo', 'Linha do tempo de usos, incluindo a Antiga Maternidade (edificação anexa).'),
    N('e2-rest', 'e2', 'ramo', 'Restauro e retrofit', 'Registro do processo de restauração e adaptação para o CIP.'),
    N('e3-frevo', 'e3', 'ramo', 'Frevo', 'História, características e importância; quem construiu essa história.'),
    N('e3-bonecos', 'e3', 'ramo', 'Bonecos Gigantes', 'História e mestres bonequeiros de Olinda.'),
    N('e3-mar', 'e3', 'ramo', 'Maracatu', 'O Maracatu como patrimônio imaterial de Olinda.'),
    N('e3-cabo', 'e3', 'ramo', 'Caboclinhos', 'História, características e grupos.'),
    N('e3-tap', 'e3', 'ramo', 'Tapioca Olindense', 'História, tapioqueiras do Alto da Sé, modos de fazer.'),
    N('e3-mestres', 'e3', 'ramo', 'Personagens e mestres', 'As pessoas que construíram essa história, com suas contribuições.'),
    N('e4-cron', 'e4', 'ramo', 'Cronologia 1535–hoje', 'Fatos: fundação 1535, invasão holandesa 1630, incêndio 1631, expulsão 1654, IPHAN 1968, UNESCO 14/12/1982.'),
    N('e4-ico', 'e4', 'ramo', 'Ilustração por marco', 'Cada fato histórico precisa de ao menos uma imagem, ainda que representativa.'),
    N('e5-carto', 'e5', 'ramo', 'Cartografia antiga', 'Cartografia mais antiga de Olinda; referências topográficas naturais originais.'),
    N('e5-fauna', 'e5', 'ramo', 'Fauna e flora', 'Paisagem idílica natural do período de fundação.'),
    N('e5-povos', 'e5', 'ramo', 'Caetés e escravizados', 'Povos originários (Caetés), povos escravizados, primeiras ocupações.'),
    N('e5-cana', 'e5', 'ramo', 'Produção canavieira', 'Início da economia açucareira.'),
    N('e5-hol', 'e5', 'ramo', 'Período holandês 1630–54', 'Invasão holandesa (1630) e expulsão (1654).'),
    N('e5-post', 'e5', 'ramo', 'Pinturas de Frans Post', 'Arquivo com TODAS as pinturas de Frans Post sobre Olinda (séc. XVII) — citações imagéticas poéticas.', { relev: 3 }),
    N('e6-plantas', 'e6', 'ramo', 'Plantas e mapas históricos', 'Plantas e imagens aéreas da fundação à atualidade.'),
    N('e6-planos', 'e6', 'ramo', 'Planos diretores', 'Planos diretores e planos de intervenção urbana.'),
    N('e6-transf', 'e6', 'ramo', 'Transformações urbanas', 'Aberturas de avenidas, ruas, praças e logradouros.'),
    N('e6-se', 'e6', 'ramo', 'Alto da Sé', 'Ponto de partida narrativo — coração histórico da cidade.', { relev: 3 }),
    N('e7-linhas', 'e7', 'ramo', 'Linhas e estações', 'Mapa das estações e linhas do Bonde Elétrico (1914–1950).'),
    N('e7-ico', 'e7', 'ramo', 'Iconografia do percurso', 'Fotos, vídeos, pinturas das ruas, pontes e estações do trajeto.'),
    N('e7-arq', 'e7', 'ramo', 'Arquitetura do trajeto', 'Tipologias, estilos, cores, mão de obra das construções do percurso.'),
    N('e7-capiba', 'e7', 'ramo', 'Capiba', '"Quem vai pra Farol é o Bonde de Olinda" — referência musical da instalação.'),
    N('e8-bio', 'e8', 'ramo', 'Biografia', 'Sinopse biográfica de Aloísio Magalhães.'),
    N('e8-album', 'e8', 'ramo', 'Álbum Olinda', 'As litogravuras do Álbum Olinda — base dos painéis táteis.', { relev: 3 }),
    N('e8-unesco', 'e8', 'ramo', 'Luta pelo título UNESCO', 'Atuação de Aloísio no reconhecimento de Olinda como Patrimônio Mundial.'),
    N('e9-postais', 'e9', 'ramo', 'Cartões postais', 'Inventário de imagens dos antigos cartões postais de Olinda.'),
    N('e9-selos', 'e9', 'ramo', 'Selos', 'Selos antigos de Olinda.'),
    N('e9-cat', 'e9', 'ramo', 'Catalogação temática', 'Imagens catalogadas por temas para o terminal de pesquisa.'),
    N('e10-pub', 'e10', 'ramo', 'Publicações', 'Livros e publicações físicas/digitais sobre o Centro Histórico.'),
    N('e10-teses', 'e10', 'ramo', 'Teses e dissertações', 'Produção acadêmica exclusivamente sobre o Centro Histórico.'),
    N('e10-art', 'e10', 'ramo', 'Artigos e documentos', 'Artigos e documentos digitais catalogados.'),
    N('e10-av', 'e10', 'ramo', 'Audiovisual', 'Filmes, documentários e registros audiovisuais.'),
    N('e11-gastro', 'e11', 'ramo', 'Pratos e receitas', 'Principais pratos: características, receitas, histórias e modos de fazer.'),
    N('e11-pessoas', 'e11', 'ramo', 'Personagens da gastronomia', 'Nomes da gastronomia olindense.'),
    N('e11-arte', 'e11', 'ramo', 'Artistas e artesãos', 'Principais artistas e artesãos: histórias e produções.'),
    N('e12-hist', 'e12', 'ramo', 'História do grupo', 'Principais informações e características do Maracatu Nação Pernambuco.'),
    N('e12-mestres', 'e12', 'ramo', 'Mestres e membros', 'Membros e mestres do grupo.'),
    N('e12-org', 'e12', 'ramo', 'Estrutura organizacional', 'Como o grupo se organiza.'),
    N('e12-saber', 'e12', 'ramo', 'Saberes ancestrais', 'Saberes e práticas culturais ancestrais, sociais e identitárias.'),
  ],
  links: [
    { a: 'e3-mar', b: 'e12', tipo: 'direto', nota: 'O núcleo do Eixo 12 é a expressão viva do patrimônio imaterial do Eixo 3.' },
    { a: 'e3-tap', b: 'e11-gastro', tipo: 'direto', nota: '' },
    { a: 'e5-post', b: 'e6-plantas', tipo: 'indireto', nota: '' },
    { a: 'e5-carto', b: 'e6-plantas', tipo: 'direto', nota: '' },
    { a: 'e8-unesco', b: 'e4-cron', tipo: 'direto', nota: 'O título UNESCO (14/12/1982) é marco da linha do tempo.' },
    { a: 'e7-linhas', b: 'e6-transf', tipo: 'direto', nota: '' },
    { a: 'e9-postais', b: 'e7-ico', tipo: 'indireto', nota: 'Postais antigos podem conter imagens do bonde e do percurso.' },
    { a: 'e2-hist', b: 'e1-inv', tipo: 'indireto', nota: '' },
    { a: 'e12-mestres', b: 'e3-mestres', tipo: 'direto', nota: '' },
    { a: 'e10-av', b: 'e3-frevo', tipo: 'indireto', nota: '' },
  ],
};
